apiVersion: v1
kind: Pod
metadata:
  name: alpine-server
spec:
  containers:
  - name: alpine
    image: python:3-alpine
    command: ["python3", "-m", "http.server", "8080"]
    ports:
    - containerPort: 8080
